<?php

namespace AppBundle\Repository;

/**
 * moviesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class moviesRepository extends \Doctrine\ORM\EntityRepository
{
}
